workflows:
  chrome-workflow:
    name: Chrome Workflow
    max_build_duration: 120
    instance_type: windows_x2

    scripts:
      - name: Update Chrome
        script: |
          choco upgrade googlechrome -y --ignore-checksums

      - name: Install Matching ChromeDriver
        script: |
          choco upgrade chromedriver --version=146 -y
